import { Inter } from 'next/font/google';

// import type { Metadata } from 'next';


import { ProvidersWrapper } from '@/components/ProvidersWrapper';
import { RefreshWraper } from '@/components/RefreshWraper';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <RefreshWraper>
          <ProvidersWrapper>
           {children}
          </ProvidersWrapper>
        </RefreshWraper>
      </body>
    </html>
  );
}
